# PyTorch 101

### STEP 1: Load Modules

In [ ]:
# Load PyTorch module
import torch

### STEP 2: Explore Tensor Characteristics

In this section, we explore key characteristics of PyTorch tensors, including their shape, data type, dimensionality, and how to access individual elements. Understanding these properties is essential for working effectively with tensors in deep learning and numerical computing tasks.

In [ ]:
# Define a 2D list (3 rows x 2 columns)
data = [[1,2], [3,4], [5,6]]

# Convert the list into a PyTorch tensor
tensor_data = torch.tensor(data)

# Print the tensor content
print(f'Tensor Data: \n{tensor_data}')
# Display the data type (should be torch.Tensor)
print(f'Tensor Type: {type(tensor_data)}')
# Display the shape of the tensor (3, 2)
print(f'Tensor Shape: {tensor_data.shape}')
# Access the element in row index 1 and column index 1 (i.e., second row, second column)
print(f'Access Element [X-axis 2 || Y-axis 1]: {tensor_data[1][1]}')

Tensor Data: 
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Tensor Type: <class 'torch.Tensor'>
Tensor Shape: torch.Size([3, 2])
Access Element [X-axis 2 || Y-axis 1]: 4


In [ ]:
# Create a 3D tensor with shape [4, 4, 4] filled with random values
shape = (4,4,4)
rand_tensor = torch.rand(shape)

print(f'Tensor Data: \n{rand_tensor}')
# Access the 4th element along the X-axis (i.e., index 3)
print(f'Access Elements [X-axis 4]: \n{rand_tensor[3]}')
# Access the 2nd element (index 1) along the Y-axis of the 4th X-slice
print(f'Access Elements [X-axis 4 | Y-axis 1]: {rand_tensor[3][1]}')
# Access the 1st element (index 0) along the Z-axis of the [X=4, Y=2] slice
print(f'Access Elements [X-axis 4 | Y-axis 1 | Z-axis 0]: {rand_tensor[3][1][0]}')

Tensor Data: 
tensor([[[0.4997, 0.7410, 0.7306, 0.3946],
         [0.2932, 0.5696, 0.8455, 0.7932],
         [0.9440, 0.1915, 0.4548, 0.6310],
         [0.5303, 0.3856, 0.4613, 0.1263]],

        [[0.5764, 0.6639, 0.3460, 0.3583],
         [0.9575, 0.0430, 0.9089, 0.9298],
         [0.9918, 0.4859, 0.6074, 0.7605],
         [0.2766, 0.1484, 0.6388, 0.3928]],

        [[0.5828, 0.3564, 0.1146, 0.3779],
         [0.3630, 0.2981, 0.7494, 0.7664],
         [0.9418, 0.6339, 0.0835, 0.3902],
         [0.8138, 0.3381, 0.9962, 0.3698]],

        [[0.0092, 0.3211, 0.1872, 0.4029],
         [0.0466, 0.3723, 0.1464, 0.9470],
         [0.2338, 0.0149, 0.0085, 0.2869],
         [0.7536, 0.5853, 0.1648, 0.7620]]])
Access Elements [X-axis 4]: 
tensor([[0.0092, 0.3211, 0.1872, 0.4029],
        [0.0466, 0.3723, 0.1464, 0.9470],
        [0.2338, 0.0149, 0.0085, 0.2869],
        [0.7536, 0.5853, 0.1648, 0.7620]])
Access Elements [X-axis 4 | Y-axis 1]: tensor([0.0466, 0.3723, 0.1464, 0.9470])
Access Eleme

### Excersice 1

In [ ]:
# TODO:
# Create a tensor with shape torch.Size([3, 3])
# Access the following elements:
# 1) Element at row 1, column 3  → tensor[0][2]
# 2) Element at row 3, column 2  → tensor[2][1]

### Excersice 2

In [ ]:
# TODO:
# Create two tensors with shape (5, 2, 3): one filled with zeros and the other with ones.
# Display (visualize) both tensors.
# Hint: Use .zeros or .ones instead of .rand to initialize the tensors.

### STEP 3: Tensor Arithmetic

In [ ]:
tensor_a = torch.arange(10)
tensor_b = torch.linspace(10,19,10)

tensor_c = tensor_a / tensor_b
print(f'Tensor Addition: {tensor_c}')

Tensor Addition: tensor([0.0000, 0.0909, 0.1667, 0.2308, 0.2857, 0.3333, 0.3750, 0.4118, 0.4444,
        0.4737])


### Excersice 3

In [ ]:
# TODO:
# Perform element-wise subtraction, multiplication, and division between tensor_a and tensor_b.

### STEP 4: Torch Methods

In [ ]:
# Create a 1D tensor with 12 random values
torch_tensor = torch.rand(12)
print(f'Original Tensor: \n{torch_tensor}')
print(f'Original Tensor Shape: {torch_tensor.shape}')

# Reshape the tensor to shape (3, 4, 1)
reshape_tensor = torch.reshape(torch_tensor, (3,4,1))
print(f'Reshape Tensor: \n{reshape_tensor}')
print(f'Reshape Tensor Shape: {reshape_tensor.shape}')

Original Tensor: 
tensor([0.6552, 0.7459, 0.8339, 0.4281, 0.0934, 0.2279, 0.6972, 0.0862, 0.5770,
        0.0037, 0.8553, 0.8084])
Original Tensor Shape: torch.Size([12])
Reshape Tensor: 
tensor([[[0.6552],
         [0.7459],
         [0.8339],
         [0.4281]],

        [[0.0934],
         [0.2279],
         [0.6972],
         [0.0862]],

        [[0.5770],
         [0.0037],
         [0.8553],
         [0.8084]]])
Reshape Tensor Shape: torch.Size([3, 4, 1])


### Other Important Torch Methods

I recommend reviewing the following documents, as they cover commonly used PyTorch methods for tensor manipulation during the development of deep learning models.

1) Squeeze: https://docs.pytorch.org/docs/stable/generated/torch.squeeze.html
2) Unsqueeze: https://docs.pytorch.org/docs/stable/generated/torch.unsqueeze.html#torch.unsqueeze
3) Concatenate: https://docs.pytorch.org/docs/stable/generated/torch.cat.html
4) transpose: https://docs.pytorch.org/docs/stable/generated/torch.transpose.html#torch.transpose