# PyTorch 101

In my opinion, PyTorch is one of the most, if not the most, sought-after skills in today’s market. Proficiency in this library significantly increases your chances of securing a job or internship, even in the current job market. From job openings at tech companies like NVIDIA and Meta to national labs such as Oak Ridge National Laboratory, PyTorch is frequently listed as a required skill.

The library itself is extensive, and I believe a one-week bootcamp may not be sufficient to cover it in depth. Therefore, it’s not feasible to address every aspect of PyTorch in this short tutorial. However, this tutorial aims to introduce you to PyTorch tensors, the fundamental data structure used in deep learning. 

In this tutorial, we explore the characteristics and operations of tensors, along with commonly used methods for tensor manipulation. This includes understanding tensor shape, dimensionality, accessing individual elements, performing mathematical operations, and reshaping tensors. The tutorial introduces foundational yet widely applicable tasks that are commonly used in both model training and code debugging.

In [3]:
# Load PyTorch module
import torch

## Tensor Characteristics  
Read through the examples below, then complete the exercises using what you’ve learned.

## Example 1  

In this example, you’ll make a PyTorch tensor from a Python list and then explore how to reference different elements in the tensor.

Note: Python uses zero-based indexing, so the indices run from 0 upward. That’s why index `[1][1]` references the element in the second row and second column.


In [7]:
# Define a 2D list (3 rows x 2 columns)
data = [[1,2], [3,4], [5,6]]

# Convert the list into a PyTorch tensor
tensor_data = torch.tensor(data)

# Print the tensor content
print(f'Tensor Data: \n{tensor_data}')
# Display the data type (should be torch.Tensor)
print(f'Tensor Type: {type(tensor_data)}')
# Display the shape of the tensor (3, 2)
print(f'Tensor Shape: {tensor_data.shape}')
# Access the element in row index 1 and column index 1 (i.e., second row, second column)
print(f'Access Element [X-axis 1 || Y-axis 1]: {tensor_data[1][1]}')

Tensor Data: 
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Tensor Type: <class 'torch.Tensor'>
Tensor Shape: torch.Size([3, 2])
Access Element [X-axis 1 || Y-axis 1]: 4


## Example 2

- `shape = (4, 4, 4)` is a tuple that defines the dimensions of the tensor we want to create.
  - It means: **4 blocks (or layers)**, each with **4 rows** and **4 columns**.
  - You can think of this as a 3D cube with X, Y, and Z axes.

- `torch.rand(shape)` is a PyTorch function that creates a tensor filled with **random numbers between 0 and 1**.
  - This will generate a tensor of shape `4 × 4 × 4`, matching the structure we specified.

- The resulting `rand_tensor` is like a 3D array or cube.
  - To access the 4th layer, we use `rand_tensor[3]`.

> In the comments below, we give the X, Y, and Z coordinates in the way you would think of them if plotted on a 3D graph — with 0 at the origin and the first element labeled as 1, the second as 2, and so on.  
> However, Python uses **zero-based indexing**, so the first element of the X-axis is at index `0`, the second at index `1`, and so on — always one behind the axis label.


In [9]:
# Create a 3D tensor with shape [4, 4, 4] filled with random values
shape = (4,4,4)
rand_tensor = torch.rand(shape)

print(f'Tensor Data: \n{rand_tensor}')
# Access the all elements of the of the 4th X-slice (i.e., index 3)
print(f'Access Elements [X-axis 4]: \n{rand_tensor[3]}')
# Access the 2nd element (index 1) along the Y-axis of the 4th X-slice
print(f'Access Elements [X-axis 4 | Y-axis 2]: {rand_tensor[3][1]}')
# Access the 1st element (index 0) along the Z-axis of the [X=4, Y=2] slice
print(f'Access Elements [X-axis 4 | Y-axis 2 | Z-axis 1]: {rand_tensor[3][1][0]}')

Tensor Data: 
tensor([[[9.6080e-01, 9.2070e-01, 1.3224e-01, 3.1468e-01],
         [6.5770e-01, 5.9393e-01, 8.4609e-01, 9.1408e-01],
         [9.7229e-01, 6.7841e-02, 2.6427e-01, 4.7259e-01],
         [7.4294e-01, 3.8384e-01, 7.0606e-01, 4.7537e-01]],

        [[7.0542e-01, 3.7015e-01, 8.1564e-01, 2.9951e-01],
         [7.2222e-01, 8.5313e-01, 4.2674e-01, 8.6185e-01],
         [7.0511e-01, 2.5638e-01, 2.3325e-01, 5.0352e-01],
         [6.0282e-01, 6.6364e-01, 9.9505e-01, 9.2501e-01]],

        [[7.4308e-01, 3.1095e-01, 3.7137e-02, 1.2274e-01],
         [2.8374e-01, 5.5940e-01, 2.9412e-01, 2.2812e-01],
         [5.0115e-02, 9.4015e-01, 2.4921e-04, 6.7302e-01],
         [8.5307e-02, 2.4080e-01, 7.1519e-01, 7.8064e-01]],

        [[7.5131e-01, 6.5484e-01, 8.5819e-01, 9.2618e-01],
         [9.4572e-01, 4.7035e-01, 5.1906e-01, 1.7131e-01],
         [7.4271e-01, 6.8720e-01, 8.6346e-01, 8.5431e-01],
         [9.8770e-01, 1.3601e-01, 9.8604e-01, 3.6114e-01]]])
Access Elements [X-axis 4]: 
tenso

## Excersice 1

In [69]:
# TODO:
# Create a tensor with shape torch.Size([3, 3])
# Access the following elements:
# 1) Element at row 1, column 3  → tensor[0][2]
# 2) Element at row 3, column 2  → tensor[2][1]

## Excersice 2

In [70]:
# TODO:
# Create two tensors with shape (5, 2, 3): one filled with zeros and the other with ones.
# Display (visualize) both tensors.
# Hint: Use .zeros or .ones instead of .rand to initialize the tensors.

## Tensor Operations

### Example 3
In tensor operations like addition, the operation is performed element-wise:

* tensor_a[0] is added to tensor_b[0]
* tensor_a[1] is added to tensor_b[1]
and so on.

This principle applies to other operations like subtraction, multiplication, and division as well—each operation is applied to the corresponding elements of the tensors, assuming they are broadcast-compatible.

In [11]:
tensor_a = torch.arange(10)
tensor_b = torch.linspace(10,19,10)

print(f'tensor_a \n{tensor_a}')
print(f'tensor_b \n{tensor_b}')


tensor_c = tensor_a + tensor_b
print(f'Tensor Addition: {tensor_c}')

tensor_a 
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor_b 
tensor([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])
Tensor Addition: tensor([10., 12., 14., 16., 18., 20., 22., 24., 26., 28.])


## Excersice 3

In [72]:
# TODO:
# Perform element-wise subtraction, multiplication, and division between tensor_a and tensor_b.

## Torch Methods

In [73]:
# Create a 1D tensor with 12 random values
torch_tensor = torch.rand(12)
print(f'Original Tensor: \n{torch_tensor}')
print(f'Original Tensor Shape: {torch_tensor.shape}')

# Reshape the tensor to shape (3, 4, 1)
reshape_tensor = torch.reshape(torch_tensor, (3,4,1))
print(f'Reshape Tensor: \n{reshape_tensor}')
print(f'Reshape Tensor Shape: {reshape_tensor.shape}')

Original Tensor: 
tensor([0.9151, 0.9863, 0.4043, 0.9076, 0.4545, 0.6225, 0.0901, 0.3454, 0.6647,
        0.5650, 0.9004, 0.5153])
Original Tensor Shape: torch.Size([12])
Reshape Tensor: 
tensor([[[0.9151],
         [0.9863],
         [0.4043],
         [0.9076]],

        [[0.4545],
         [0.6225],
         [0.0901],
         [0.3454]],

        [[0.6647],
         [0.5650],
         [0.9004],
         [0.5153]]])
Reshape Tensor Shape: torch.Size([3, 4, 1])


## Excersice 4

In [74]:
# TODO
# Create a tensor of size (3, 4) and print the tensor and its shape
# Transpose the tensor using 3 different combinations of dimensions of your choice
# Transpose documentation: https://pytorch.org/docs/stable/generated/torch.transpose.html
# Print each transposed tensor and its shape to visualize the differences 
# between the transposed versions and the original tensor

# TODO
# Create a tensor of size (3, 1, 1) and print the tensor and its shape
# Concatenate 4 such rand_tensors into one tensor
# Concatenate: https://pytorch.org/docs/stable/generated/torch.cat.html
# Print the concatenated tensor and its shape using dim=0, dim=1, and dim=2 
# to visualize the difference between the concatenated tensor and the original