# PyTorch 101

In my opinion, PyTorch is one of the most, if not the most, sought-after skills in today’s market. Proficiency in this library significantly increases your chances of securing a job or internship, even in the current job market. From job openings at tech companies like NVIDIA and Meta to national labs such as Oak Ridge National Laboratory, PyTorch is frequently listed as a required skill.

The library itself is extensive, and I believe a one-week bootcamp may not be sufficient to cover it in depth. Therefore, it’s not feasible to address every aspect of PyTorch in this short tutorial. However, this tutorial aims to introduce you to PyTorch tensors, the fundamental data structure used in deep learning. 

In this tutorial, we explore the characteristics and operations of tensors, along with commonly used methods for tensor manipulation. This includes understanding tensor shape, dimensionality, accessing individual elements, performing mathematical operations, and reshaping tensors. The tutorial introduces foundational yet widely applicable tasks that are commonly used in both model training and code debugging.

In [1]:
# Load PyTorch module
import torch

## Tensor Characteristics

In [2]:
# Define a 2D list (3 rows x 2 columns)
data = [[1,2], [3,4], [5,6]]

# Convert the list into a PyTorch tensor
tensor_data = torch.tensor(data)

# Print the tensor content
print(f'Tensor Data: \n{tensor_data}')
# Display the data type (should be torch.Tensor)
print(f'Tensor Type: {type(tensor_data)}')
# Display the shape of the tensor (3, 2)
print(f'Tensor Shape: {tensor_data.shape}')
# Access the element in row index 1 and column index 1 (i.e., second row, second column)
print(f'Access Element [X-axis 2 || Y-axis 1]: {tensor_data[1][0]}')

Tensor Data: 
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Tensor Type: <class 'torch.Tensor'>
Tensor Shape: torch.Size([3, 2])
Access Element [X-axis 2 || Y-axis 1]: 3


In [3]:
# Create a 3D tensor with shape [4, 4, 4] filled with random values
shape = (4,4,4)
rand_tensor = torch.rand(shape)

print(f'Tensor Data: \n{rand_tensor}')
# Access the 4th element along the X-axis (i.e., index 3)
print(f'Access Elements [X-axis 4]: \n{rand_tensor[3]}')
# Access the 2nd element (index 1) along the Y-axis of the 4th X-slice
print(f'Access Elements [X-axis 4 | Y-axis 2]: {rand_tensor[3][1]}')
# Access the 1st element (index 0) along the Z-axis of the [X=4, Y=2] slice
print(f'Access Elements [X-axis 4 | Y-axis 2 | Z-axis 1]: {rand_tensor[3][1][0]}')

Tensor Data: 
tensor([[[0.8003, 0.7550, 0.6769, 0.4631],
         [0.2441, 0.7786, 0.4436, 0.6635],
         [0.4237, 0.2438, 0.0729, 0.9116],
         [0.5505, 0.2375, 0.1711, 0.6389]],

        [[0.5602, 0.5307, 0.1511, 0.4389],
         [0.8567, 0.6476, 0.4690, 0.9452],
         [0.9064, 0.4207, 0.7354, 0.8785],
         [0.6521, 0.9748, 0.0761, 0.0314]],

        [[0.7117, 0.1811, 0.1521, 0.6872],
         [0.8134, 0.4626, 0.4363, 0.1979],
         [0.8086, 0.8918, 0.8568, 0.8279],
         [0.7901, 0.6400, 0.7215, 0.6722]],

        [[0.6651, 0.2482, 0.8108, 0.0530],
         [0.0704, 0.6788, 0.0736, 0.4344],
         [0.1410, 0.5490, 0.8598, 0.0946],
         [0.3038, 0.9114, 0.2572, 0.5186]]])
Access Elements [X-axis 4]: 
tensor([[0.6651, 0.2482, 0.8108, 0.0530],
        [0.0704, 0.6788, 0.0736, 0.4344],
        [0.1410, 0.5490, 0.8598, 0.0946],
        [0.3038, 0.9114, 0.2572, 0.5186]])
Access Elements [X-axis 4 | Y-axis 2]: tensor([0.0704, 0.6788, 0.0736, 0.4344])
Access Eleme

## Excersice 1

In [69]:
# TODO:
# Create a tensor with shape torch.Size([3, 3])
# Access the following elements:
# 1) Element at row 1, column 3  → tensor[0][2]
# 2) Element at row 3, column 2  → tensor[2][1]

## Excersice 2

In [70]:
# TODO:
# Create two tensors with shape (5, 2, 3): one filled with zeros and the other with ones.
# Display (visualize) both tensors.
# Hint: Use .zeros or .ones instead of .rand to initialize the tensors.

## Tensor Operations

In [4]:
tensor_a = torch.arange(10)
tensor_b = torch.linspace(10,19,10)

tensor_c = tensor_a + tensor_b
print(f'Tensor Addition: {tensor_c}')

Tensor Addition: tensor([10., 12., 14., 16., 18., 20., 22., 24., 26., 28.])


## Excersice 3

In [72]:
# TODO:
# Perform element-wise subtraction, multiplication, and division between tensor_a and tensor_b.

## Torch Methods

In [ ]:
# Create a 1D tensor with 12 random values
torch_tensor = torch.rand(12)
print(f'Original Tensor: \n{torch_tensor}')
print(f'Original Tensor Shape: {torch_tensor.shape}')

# Reshape the tensor to shape (3, 4, 1)
reshape_tensor = torch.reshape(torch_tensor, (3,4,1))
print(f'Reshape Tensor: \n{reshape_tensor}')
print(f'Reshape Tensor Shape: {reshape_tensor.shape}')

## Excersice 4

In [74]:
# TODO
# Create a tensor of size (3, 4) and print the tensor and its shape
# Transpose the tensor using 3 different combinations of dimensions of your choice
# Transpose documentation: https://pytorch.org/docs/stable/generated/torch.transpose.html
# Print each transposed tensor and its shape to visualize the differences 
# between the transposed versions and the original tensor

# TODO
# Create a tensor of size (3, 1, 1) and print the tensor and its shape
# Concatenate 4 such rand_tensors into one tensor
# Concatenate: https://pytorch.org/docs/stable/generated/torch.cat.html
# Print the concatenated tensor and its shape using dim=0, dim=1, and dim=2 
# to visualize the difference between the concatenated tensor and the original

## Next Step: 
`/BuildingsBenchTutorial/Tutorials/Intro-Modules/Intro-NN.ipynb`